### PR TITLE
Rewrite website to match latest mockups

### PR DESCRIPTION
**Pull request by tfuxu**
This is a complete rewrite of `gradience.atrophaneura.tech` website to match daudix-UFO latest [mockup](https://github.com/GradienceTeam/Design/blob/main/Mockups/web/gradience/gradience.png).
The current state of this PR is highly WIP, as it's missing some important things (like, for example an entire Themes subpage), and it isn't yet fully optimized for phones.

## Things to do before merging:

- [x] Update website to match latest mockup revision
- [ ] Make website more dynamic:
  - [x]  Parallax scrolling effect for background image in first section ('splash')
  - [x] Button hover animations
  - [ ] (maybe) An video instead of an static image in laptop
  - [ ] Animated clouds in the last section
- [ ] Fix shadows behind titles with gradient applied moving itself when resizing the window
- [ ] Complete `Themes` subpage
- [ ] Optimize some elements for mobile users
- [ ] Get local `fontawesome` icons to work (I'm currently using my kit here, which isn't ideal)
- [x] ~Create a dark mode (not sure about that)~
- [ ] Check compatibility with other web engines (I'm testing and debugging this website in Firefox, so we'll need to test it  in Chromium and Webkit based browsers)
- [ ] Clean up the code (remove unused or commented out properties and elements)

### CODE REVIEW

**Comment by 0xMRTT** [comment]
What about using React or something like that ?

**Comment by tfuxu** [comment]
I don't see why would we need to create it in React. If we were building a big web app (something like Github or Spotify), then it would be more understandable to use React or some other JS framework, but a small website can be written entirely in HTML, CSS and JS.

**Comment by 0xMRTT** [comment]
Yeah!

**Comment by tfuxu** [comment]
Just as a PR status update, I stalled progress on this rewrite for now, because I'm now working on new features for Gradience, and we might also rework a mockup soon, so I just don't think that it will be productive to do currently something that we will do from a ground up anyway, but if we decide on a certain design soon, I might end this rewrite somewhere between February and March.

**Pull request closed without merging**
