### PR TITLE
Update a style and make it more responsive

### PR DESCRIPTION
**Pull request by tfuxu**
Updated design:
Screenshot from 2023-02-19 23-41-11

Ping @daudix-UFO

### CODE REVIEW

**Comment by daudix** [comment]
@tfuxu I have done some tweaks, will push them soon, overall looks very good

**Comment by daudix** [comment]
image

**Comment by daudix** [comment]
@tfuxu can you review my changes? if they are ok we can merge

**Comment by tfuxu** [comment]
> @tfuxu can you review my changes? if they are ok we can merge

Sure, I'll review it after dinner :^) Give me approx. 30 minutes, and everything should be ready to merge.

**Comment by tfuxu** [comment]
Looks good. LGTM

**Pull request merged**
